on:
    issues:
        types: [opened]

jobs:
    issue_is_opened:
        name: Fetch opened issue detail
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: ./ # Uses an action in the root directory
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                canonical-name: 'create-banner-image-from-grithub-action'
                gradient-colors: '#fc00ff,#00dbde'
                article-name: 'Create Banner Image From Github Action'
                article-category: 'open-source'
                emoji: '🎉'